version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      # Model configuration - Using lightweight TinyLlama for production
      - GGUF_REPO=TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF
      - GGUF_FILE=tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
      - N_CTX=2048
      - N_GPU_LAYERS=0  # Set to >0 if you have CUDA support
      
      # Production security settings
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}  # REQUIRED: Set this in your environment!
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}  # REQUIRED: Set your domain(s)
    volumes:
      # Mount volume for model cache to persist downloads
      - model_cache:/home/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  model_cache:
    driver: local