version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Model configuration - Using lightweight TinyLlama (~600MB)
      - GGUF_REPO=TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF
      - GGUF_FILE=tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
      - N_CTX=2048
      - N_GPU_LAYERS=0  # Set to >0 if you have CUDA support
      
      # Production security settings
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-}  # Set this in production!
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5000,http://127.0.0.1:5000}
    volumes:
      # Mount volume for model cache to persist downloads
      - model_cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache:
    driver: local